# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e2e79f14318f8ef519408c89ff4dc54eae9f3e0426d418d515d248e1e358c1193584c5afdfa219ebeb651000a067174c46117e957b835ef06cda5e7066a8a28
  hashnest_username: <%= ENV['HASHNEST_USERNAME'] %>
  hasnest_api_key: <%= ENV['HASHNEST_API_KEY'] %>
  hashnest_api_secret: <%= ENV['HASHNEST_API_SECRET'] %>

test:
  secret_key_base: cbd84f044117eab84e05272cff27921da7e09427262e8e72e3861c36f50748828d685bdc75aa78443126e89f24534f98b57dab43e373e4bc325b6eaf1d434717
  hashnest_username: <%= ENV['HASHNEST_USERNAME'] %>
  hasnest_api_key: <%= ENV['HASHNEST_API_KEY'] %>
  hashnest_api_secret: <%= ENV['HASHNEST_API_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  hashnest_username: <%= ENV['HASHNEST_USERNAME'] %>
  hasnest_api_key: <%= ENV['HASHNEST_API_KEY'] %>
  hashnest_api_secret: <%= ENV['HASHNEST_API_SECRET'] %>